name: Publish Hive 2.x Client

on:
  push:
    tags:
      - "rel/release-2.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "8"

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}